name: Bug Report
description: Reportar um erro ou comportamento inesperado no sistema
title: "[BUG]: "
labels: ["🐞 bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar um bug! Por favor, preencha os campos abaixo para nos ajudar a entender e resolver o problema.

  - type: textarea
    id: context
    attributes:
      label: Contexto/Problema
      description: Descreva claramente qual é o problema e em que contexto ele ocorre
      placeholder: "Exemplo: Ao tentar fazer login no sistema, o botão não responde..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Liste os passos necessários para reproduzir o bug
      placeholder: |
        1. Vá para '...'
        2. Clique em '...'
        3. Observe que '...'
    validations:
      required: true

  - type: textarea
    id: expected-actual
    attributes:
      label: Resultado Esperado vs Atual
      description: O que deveria acontecer e o que realmente acontece?
      placeholder: |
        **Esperado:** O sistema deveria...
        **Atual:** Na realidade, o sistema...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Ambiente
      description: Informações sobre o ambiente onde o bug ocorre
      placeholder: "Ex: Chrome 120, Windows 11, Produção v1.2.3"
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Qual a urgência deste bug?
      options:
        - P0 - Crítico (sistema fora do ar ou perda de dados)
        - P1 - Alto (funcionalidade importante quebrada)
        - P2 - Médio (problema que afeta alguns usuários)
        - P3 - Baixo (problema menor ou cosmético)
    validations:
      required: true
