name: Story
description: Propor uma nova funcionalidade ou melhoria significativa
type: story
body:
  - type: markdown
    attributes:
      value: |
        Story:

        Contexto:

        Critérios de aceitação:

  - type: textarea
    attributes:
      id: technical_notes
      label: "Notas técnicas"
      description: "Notas técnicas"

  - type: textarea
    attributes:
      id: unit_tests
      label: "Testes unitários"
      description: "Checklist de testes unitários a serem implementados"
      value: "- [ ] \n"
