name: Story
description: Propor uma nova funcionalidade ou melhoria significativa
type: story
body:
  - type: textarea
    attributes:
      id: description
      label: "Descrição"
      description: "Descreva a story, contexto e critérios de aceitação"
      value: |
        ## Story:


        ## Contexto:


        ## Critérios de aceitação:

    validations:
      required: true

  - type: textarea
    attributes:
      id: technical_notes
      label: "Notas técnicas"
      description: "Notas técnicas"
    validations:
      required: true

  - type: textarea
    attributes:
      id: unit_tests
      label: "Testes"
      description: "Checklist de testes unitários/outros a serem implementados"
      value: "[O Desenvolvedor deve preencher quais os principais testes a serem implementados.]::\n- [ ] \n"
